name: isbndb
description: Dart service for isbndb.com API. Returns book details from an ISBN, or a list of books from an author name, etc.
version: 0.3.1
repository: https://github.com/julienlebren/flutter_ISBNdb
issue_tracker: https://github.com/julienlebren/flutter_ISBNdb/issues

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter  
  dio: ^5.7.0
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  universal_io: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter: 
